### ISSUE TITLE
Converts more KSM than "allowed"

### ISSUE THREAD

**Issue by mafux777** [timbotro/kt-vault-runner#3]
🏠 KAR Address: sR3Zm142oSLCG7Rt6Cu86tyYYD3cxmQ3DTyuiXaKeCfP5Ga
🚗 KAR Balance (for fees): 0.94
🧮 Karura KINT Price: 0.05457 KSM / $3.68
🦎 Chain vs CoinGecko price: 0.19%
🌾 Harvestable Amount: 33.35 KINT / 1.82 KSM / $122.39
=============================
? Would you like to proceed with harvesting, bridging, swapping and depositing? Yes
? How much KINT would you like to harvest and convert to KSM? (min:1 | max: 32.83)  32.7
=============================
(1/4) Claiming and Bridging rewards....Txns built. Waiting...
Txns in unfinalized block: 0x4f5858faa0780a06fc597357fdc3eaf077ac3c6874a9e8cb9c7ec7b1e6bfa761 waiting...
Done: https://cdpt.in/MTkxMTIxNg== ✅
(2/4) Swapping 32.6 KINT for KSM....Txns built. Waiting...
Txns in unfinalized block: 0x679611da77926d06a0fbcd0e3644cc855f59bc6199dcb0afd273306cd3c869ee waiting...
Done: https://cdpt.in/MTkxMTIxNw== ✅
(3/4) Bridging back 3.19319 KSM....Txns built. Waiting...
Txns in unfinalized block: 0x6089bacacae77e874351a8d5d87687e6453d2fe79ef18fe1b95c03944ae4a502 waiting...
Done: https://cdpt.in/MTkxMTIxOQ== ✅
(4/4) Depositing 3.19303 KSM Collateral back into vault...Txns built. Waiting...
Txns in unfinalized block: 0xad47dc6af526519a1b2f76a9be278ab4b12fafc540b1c39ec528df137baf674a waiting...
Done: https://cdpt.in/MTkxMTIyMA== ✅
✅  Collateral Ratio is now: 240.27%

As you can see in this example, I was expecting about 1.82 KSM to be bridged from Karura to Kintsugi.
However, KT Vault Runner found some KSM "lying around" on Kusama and decided for my own benefit to stick it into my Kintsugi vault.
It's overstepping its authority there ;)

**Comment by timbotro** [comment]
Fixed in https://github.com/timbotro/kt-vault-runner/pull/4

modified `harvest` and `rebalance` so that it will only use the resulting amount bridged (after fees).

Thanks for raising this!
